var data = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf", "vingt", "cent", "mille", "le Vert", "l'Orange", "le Blanc", "le Rouge", "le Jaune", "le Bleu", "le Noir", "le Gris", "le Rose", "le Brun", "le Pourpre", "le/la numéro", "les coleurs", "Lundi", "Mardi", "Mecredi", "Jeudi", "Vendredi", "Samedi", "Dimanche", "janvier", "février", "mars",	"avril", "mai", "juin",	"juillet", "août","septembre", "novembre", "octobre", "décembre", "demain", "aujord'hui", "le garçon", "la fille", "la femme", "l'homme", "le frère", "la sœur", "le père", "la mère", "la grand-mère", "le grand-père", "l'hiver", "le printemps", "l'automne", "l'été", "l'heure", "la minute", "le soleil", "la nuit", "le jour", "l'ordinateur", "le télé", "la radio", "le chien", "le chat", "le hamster", "le canard", "l'oiseau", "la vache", "le lion", "le tigre", "le mouton", "le cochon", "le loup", "la lune", "le monde", "la musique", "la école", "le poisson", "le lapin", "la souris", "le serpent", "le poulet", "le kangouroo", "le renard", "le papillon",
"desolee", "bien", "au revoir", "bonjour", "salut", "S'il vous plaît", "merci", "beaucoup", "à bientôt", "oui", "non", "à demain",
"je", "tu", "nous", "vous", "il", "elle", "elles", "ils", "moi", "toi", "tout le monde", "et"
	];

var movieData = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf", "vingt", "cent", "mille", "le Vert", "l'Orange", "le Blanc", "le Rouge", "le Jaune", "le Bleu", "le Noir", "le Gris", "le Rose", "le Brun", "le Pourpre", "le/la numéro", "les coleurs", "Lundi", "Mardi", "Mecredi", "Jeudi", "Vendredi", "Samedi", "Dimanche", "janvier", "février", "mars",	"avril", "mai", "juin",	"juillet", "août","septembre", "novembre", "octobre", "décembre", "demain", "aujord'hui", "le garçon", "la fille", "la femme", "l'homme", "le frère", "la sœur", "le père", "la mère", "la grand-mère", "le grand-père", "l'hiver", "le printemps", "l'automne", "l'été", "l'heure", "la minute", "le soleil", "la nuit", "le jour", "l'ordinateur", "le télé", "la radio", "le chien", "le chat", "le hamster", "le canard", "l'oiseau", "la vache", "le lion", "le tigre", "le mouton", "le cochon", "le loup", "la lune", "le monde", "la musique", "la école", "le poisson", "le lapin", "la souris", "le serpent", "le poulet", "le kangouroo", "le renard", "le papillon",
"desolee", "bien", "au revoir", "bonjour", "salut", "S'il vous plaît", "merci", "beaucoup", "à bientôt", 
"je", "tu", "nous", "vous", "il", "elle", "elles", "ils", "moi", "toi"
	];

var defaultData = ["English", "French", "England", "France", "Canada", "Ontario", "Québec", "Spain", "Spanish", "German", "Germany", "North America", "South America", "North", "South", "East", "West", "Europe", "Asia", "Africa", "school", "teacher", "book", "folder", "up", "down", "left", "right", "student", "classroom", "pencil", "pen", "marker", "desk", "window", "inside", "outside", "garden", "basketball", "hockey", "baseball", "sports", "mathematics", "science", "art", "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "grade", "office", "plant", "chair", "sandwich", "juice", "cookie", "radio", "television", "computer", "floor", "ceiling", "website", "light", "lamp", "blackboard", "pet", "dog", "cat", "snake", "hamster", "bird", "goat", "cow", "horse", "lion", "sheep", "January", "February", "March", "April", "May", "June", "July", "August", "September", "Octtober", "November", "December", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday", "first", "second", "third", "little", "pig", "house", "he", "she", "they", "we", "you", "your", "my", "Autumn", "Spring", "Summer", "Winter", "hot", "cold", "how", "why", "where", "when", "what", "owl", "hair", "eyes", "nose", "fingers", "toes", "feet", "legs", "body", "hands", "arms", "ears", "glasses", "glass", "cup", "chocolate", "milk", "strawberry", "cherry", "apple", "potato", "vegetable", "fruit", "noon", "midnight", "night", "morning", "hello", "goodbye", "good", "well", "bad", "sorry", "camera", "rice", "water", "popsicle", "swim", "eat", "want", "think", "understand", "hat", "coat", "shirt", "pants", "socks", "bug", "butterfly", "fly", "airplane", "travel", "work", "picture", "movie", "tail", "couch", "shoes", "tomato", "banana", "pineapple", "mango", "orange", "blue", "red", "pink", "brown", "black", "white", "purple", "yellow", "green", "grey", "watch", "see", "drink", "toilet", "bed", "home", "parent", "dad", "mom", "grandma", "grandpa", "brother", "sister", "cousin", "big", "large", "tiny", "bottle", "fire", "dark", "light", "feather", "teeth", "paint", "sit", "stand", "sleep", "door", "cloud", "sun", "moon", "frog", "wolf", "rabbit", "open", "close", "in", "on", "behind", "top", "bottom", "car", "truck", "bike", "walk", "run", "head", "jump", "shark", "fish", "star", "planet", "everyone", "world", "grow", "shrink", "time", "hour", "minute"
	];

var spanishData = ["zéro", "un", "deux", "trois", "quatre", "cinq", "six", "sept", "huit", "neuf", "dix", "onze", "douze", "treize", "quatorze", "quinze", "seize", "dix-sept", "dix-huit", "dix-neuf", "vingt", "cent", "mille", "le Vert", "l'Orange", "le Blanc", "le Rouge", "le Jaune", "le Bleu", "le Noir", "le Gris", "le Rose", "le Brun", "le Pourpre", "le/la numéro", "les coleurs", "Lundi", "Mardi", "Mecredi", "Jeudi", "Vendredi", "Samedi", "Dimanche", "janvier", "février", "mars",	"avril", "mai", "juin",	"juillet", "août","septembre", "novembre", "octobre", "décembre", "demain", "aujord'hui", "le garçon", "la fille", "la femme", "l'homme", "le frère", "la sœur", "le père", "la mère", "la grand-mère", "le grand-père", "l'hiver", "le printemps", "l'automne", "l'été", "l'heure", "la minute", "le soleil", "la nuit", "le jour", "l'ordinateur", "le télé", "la radio", "le chien", "le chat", "le hamster", "le canard", "l'oiseau", "la vache", "le lion", "le tigre", "le mouton", "le cochon", "le loup", "la lune", "le monde", "la musique", "la école", "le poisson", "le lapin", "la souris", "le serpent", "le poulet", "le kangouroo", "le renard", "le papillon",
"desolee", "bien", "au revoir", "bonjour", "salut", "S'il vous plaît", "merci", "beaucoup", "à bientôt", 
"je", "tu", "nous", "vous", "il", "elle", "elles", "ils", "ça", "moi", "toi",
"où", "Pourquoi", "quoi", "quand", "Comment", "que", 
"sur", "sous", "devant", "derrière", "dans", "à", "pour", "de", "en", "avec", "par"
	];